---
- name: Add hamlib utilities service user
  user:
    name: '{{ hamlib_utils_user }}'
    home: '/nonexistent'
    shell: '/bin/false'
    groups:
      - 'dialout'
    system: true
    state: 'present'
  become: true
  notify:
    - Restart rigctld service
    - Restart rotctld service
- name: Install hamlib utilities
  package:
    name: 'libhamlib-utils'
    state: 'present'
  become: true
  register: res
  until: res is success
  retries: 3
  notify:
    - Restart rigctld service
    - Restart rotctld service
- name: Install hamlib utilities configuration
  template:
    src: 'etc/default/hamlib-utils.j2'
    dest: '/etc/default/hamlib-utils'
    mode: 0644
  become: true
  tags:
    - hamlib_utils_config
  notify:
    - Restart rigctld service
    - Restart rotctld service
- name: Add rigctld systemd service
  template:
    src: 'etc/systemd/system/rigctld.service.j2'
    dest: '/etc/systemd/system/rigctld.service'
    mode: 0644
  become: true
  notify:
    - Restart rigctld service
- name: Add rotctld systemd service
  template:
    src: 'etc/systemd/system/rotctld.service.j2'
    dest: '/etc/systemd/system/rotctld.service'
    mode: 0644
  become: true
  notify:
    - Restart rotctld service
- name: Start/stop rigctld service
  systemd:
    daemon_reload: true
    name: 'rigctld'
    enabled: '{{ not hamlib_utils_rig_disabled | default(false) }}'
    state: '{{ "started" if not hamlib_utils_rig_disabled | default(false) else "stopped" }}'
  become: true
  tags:
    - hamlib_utils_config
- name: Start/stop rotctld service
  systemd:
    daemon_reload: true
    name: 'rotctld'
    enabled: '{{ hamlib_utils_rot_enabled | default(false) }}'
    state: '{{ "started" if hamlib_utils_rot_enabled | default(false) else "stopped" }}'
  become: true
  tags:
    - hamlib_utils_config
