---
variables:
  GITLAB_CI_IMAGE_ANSIBLE: 'librespace/ansible:6.0.0'
stages:
  - static
static_ansible:
  stage: static
  image: ${GITLAB_CI_IMAGE_ANSIBLE}
  script:
    - ansible-playbook -i production.dist/inventory/hosts --syntax-check -vvv site.yml
    - ansible-lint site.yml
