---
- hosts: satnogses
  roles:
    - role: satnogs_cleanup
      tags:
        - satnogs-cleanup
    - role: common
      tags:
        - common
    - role: satnogs
      tags:
        - satnogs
    - role: docker_engine
      tags:
        - docker-engine
