---
- import_playbook: satnogs-setups.yml
- import_playbook: satnogs-clients.yml
- import_playbook: satnogs-radios.yml
- import_playbook: hamlib-utils.yml
- import_playbook: snmpd.yml
- import_playbook: gpsd.yml
