---
- name: Update APT cache
  ansible.builtin.apt:
    update_cache: true
  become: true
  register: res
  until: res is success
  retries: '{{ package_retries }}'
  delay: '{{ package_delay }}'
- name: Stop and disable services
  ansible.builtin.service:
    name: '{{ item }}'
    enabled: false
    state: 'stopped'
  become: true
  loop:
    - 'rigctld'
    - 'rotctld'
    - 'satnogs-client'
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
- name: Restart snmpd service
  ansible.builtin.service:
    name: 'snmpd'
    state: 'restarted'
  become: true
