---
- name: Add archive repositories keys
  apt_key:
    keyserver: 'pool.sks-keyservers.net'
    id: '{{ item }}'
    state: 'present'
  become: True
  register: res
  until: res is success
  retries: 3
  with_items:
    - '8B48AD6246925553'
    - '7638D0442B90D010'
  when: ansible_os_family == 'Debian'
- name: Remove jessie backports repository
  apt_repository:
    repo: 'deb http://ftp.debian.org/debian jessie-backports main'
    state: 'absent'
  become: True
  register: res
  until: res is success
  retries: 3
- name: Pin packages
  template:
    src: 'etc/apt/preferences.d/satnogs.j2'
    dest: '/etc/apt/preferences.d/satnogs'
    mode: 0644
  become: True
- name: Install gr-satnogs
  apt:
    name:
      - 'gr-satnogs'
      - 'libgnuradio-satnogs'
    state: 'present'
  become: True
  register: res
  until: res is success
  retries: 3
- name: Blacklist SDR modules
  kernel_blacklist:
    name: '{{ item }}'
    state: 'present'
  become: True
  with_items: '{{ satnogs_radio_blacklist_modules }}'
- name: Unload SDR modules
  modprobe:
    name: '{{ item }}'
    state: 'absent'
  become: True
  with_items: '{{ satnogs_radio_blacklist_modules }}'
- name: Download UHD images
  command: '/usr/bin/uhd_images_downloader'
  args:
    creates: '/usr/share/uhd/images/{{ satnogs_radio_uhd_images_tag }}.tag'
  become: True
