---
- name: Add archive repositories keys
  apt_key:
    keyserver: 'pool.sks-keyservers.net'
    id: '{{ item }}'
    state: 'present'
  become: true
  register: res
  until: res is success
  retries: 3
  with_items:
    - '8B48AD6246925553'
    - '7638D0442B90D010'
  when: ansible_lsb.id in ["Debian", "Raspbian"] and ansible_lsb.codename == "stretch"
- name: Remove jessie backports repository
  apt_repository:
    repo: 'deb http://ftp.debian.org/debian jessie-backports main'
    state: 'absent'
  become: true
  register: res
  until: res is success
  retries: 3
- name: Pin packages
  template:
    src: 'etc/apt/preferences.d/satnogs.j2'
    dest: '/etc/apt/preferences.d/satnogs'
    mode: 0644
  become: true
  tags:
    - satnogs_radio_software
- name: Check if libgnuradio-satnogs is installed
  package:
    name: 'libgnuradio-satnogs'
    state: 'present'
  check_mode: true
  register: libgnuradio_satnogs_package
  become: true
  until: libgnuradio_satnogs_package is success
  retries: 3
- name: Uninstall gr-satnogs
  package:
    name: 'gr-satnogs'
    state: 'absent'
  become: true
  when: libgnuradio_satnogs_package.changed
  tags:
    - skip_ansible_lint
- name: Install packages
  apt:
    name: '{{ satnogs_radio_packages }}'
    state: '{{ "latest" if experimental else "present" }}'
  become: true
  register: res
  until: res is success
  retries: 3
  tags:
    - satnogs_radio_software
- name: Blacklist SDR modules
  kernel_blacklist:
    name: '{{ item }}'
    state: 'present'
  become: true
  with_items: '{{ satnogs_radio_blacklist_modules }}'
- name: Unload SDR modules
  modprobe:
    name: '{{ item }}'
    state: 'absent'
  become: true
  with_items: '{{ satnogs_radio_blacklist_modules }}'
- name: Download UHD images for stretch
  command: '/usr/bin/uhd_images_downloader'
  args:
    creates: '/usr/share/uhd/images/{{ satnogs_radio_uhd_images_tag }}.tag'
  become: true
  when: ansible_lsb.id in ["Debian", "Raspbian"] and ansible_lsb.codename == "stretch"
- name: Download UHD images for buster
  command: '/usr/bin/uhd_images_downloader'
  args:
    creates: '/usr/share/uhd/images/inventory.json'
  become: true
  when: ansible_lsb.id in ["Debian", "Raspbian"] and ansible_lsb.codename == "buster"
