---
- name: Add satnogs-client service user
  user:
    name: '{{ satnogs_client_user }}'
    home: '/var/lib/{{ satnogs_client_user }}'
    shell: '/bin/false'
    groups:
      - 'plugdev'
    system: True
    state: 'present'
  become: True
  notify:
    - Restart satnogs-client service
- name: Install dependencies
  package:
    name: '{{ item }}'
    state: 'present'
  become: True
  register: res
  until: res is success
  retries: 3
  with_items: '{{ satnogs_client_packages }}'
  notify:
    - Restart satnogs-client service
- name: Check for virtualenv with no access to global site-packages
  stat:
    path: '/var/lib/{{ satnogs_client_user }}/lib/python2.7/no-global-site-packages.txt'
  register: res_no_global
- name: Remove virtualenv
  file:
    path: '/var/lib/{{ satnogs_client_user }}/{{ item }}'
    state: 'absent'
  when: res_no_global.stat.exists and res_no_global.stat.isreg
  register: res
  until: res is success
  retries: 3
  with_items:
    - 'bin'
    - 'include'
    - 'lib'
    - 'local'
    - 'share'
- name: Uninstall satnogs-client
  pip:
    name: '{{ satnogs_client_name }}'
    virtualenv: '/var/lib/{{ satnogs_client_user }}'
    virtualenv_site_packages: True
    editable: False
    state: 'absent'
  become: True
  become_user: '{{ satnogs_client_user }}'
- name: Install satnogs-client
  pip:
    name: '{{ satnogs_client_url | default(satnogs_client_name) }}'
    version: '{{ satnogs_client_version if satnogs_client_url is undefined else omit }}'
    virtualenv: '/var/lib/{{ satnogs_client_user }}'
    virtualenv_site_packages: True
    editable: False
    state: 'present'
  retries: 5
  delay: 3
  register: res
  until: res.changed is defined and res.changed
  become: True
  become_user: '{{ satnogs_client_user }}'
  notify:
    - Restart satnogs-client service
- name: Install satnogs-client configuration
  template:
    src: 'etc/default/satnogs-client.j2'
    dest: '/etc/default/satnogs-client'
    # TODO: Fix ownership
    mode: 0644
  become: True
  tags:
    - config
  notify:
    - Restart satnogs-client service
- name: Add satnogs-client systemd service
  template:
    src: 'etc/systemd/system/satnogs-client.service.j2'
    dest: '/etc/systemd/system/satnogs-client.service'
    mode: 0644
  become: True
  notify:
    - Restart satnogs-client service
- name: Use tmpfs for state directory
  mount:
    path: '{{ satnogs_client_state_dir }}'
    src: 'tmpfs'
    fstype: 'tmpfs'
    opts: 'rw,nosuid,noexec,nodev,noatime'
    state: 'mounted'
  become: True
  notify:
    - Restart satnogs-client service
- name: Start satnogs-client service
  systemd:
    daemon_reload: True
    name: 'satnogs-client'
    enabled: True
    state: 'started'
  become: True
