---
- name: Start ZRAM service
  ansible.builtin.service:
    name: 'zram'
    state: 'started'
    enabled: true
  become: true
- name: Update APT cache
  ansible.builtin.apt:
    update_cache: true
  become: true
  register: res
  until: res is success
  retries: '{{ package_retries }}'
  delay: '{{ package_delay }}'
