---
- name: Remove old ZRAM init script
  ansible.builtin.file:
    dest: '/etc/init.d/zram'
    state: 'absent'
  become: true
- name: Restart ZRAM service
  ansible.builtin.service:
    name: 'zramswap'
    state: 'restarted'
    enabled: true
  become: true
