---
compose_satnogs_rigctld_environment: >-
  {% set ns = namespace(result=[]) -%}
  {% for var in rigctld_vars_map | dict2items(key_name='value', value_name='key') -%}
  {% set ns.result =
  ns.result + [{'key': var.key, 'value': lookup('ansible.builtin.vars', var.value, default=omit) | string}] -%}
  {% endfor -%}
  {{ ns.result | items2dict }}

compose_satnogs_rotctld_environment: >-
  {% set ns = namespace(result=[]) -%}
  {% for var in rotctld_vars_map | dict2items(key_name='value', value_name='key') -%}
  {% set ns.result =
  ns.result + [{'key': var.key, 'value': lookup('ansible.builtin.vars', var.value, default=omit) | string}] -%}
  {% endfor -%}
  {{ ns.result | items2dict }}

compose_satnogs_satnogs_client_environment: >-
  {% set ns = namespace(result=[]) -%}
  {% for var in satnogs_client_vars_map | dict2items(key_name='value', value_name='key') -%}
  {% set ns.result =
  ns.result + [{'key': var.key, 'value': lookup('ansible.builtin.vars', var.value, default=omit) | string}] -%}
  {% endfor -%}
  {{ ns.result | items2dict }}

compose_satnogs_params:
  name: 'satnogs'
  rigctld:
    name: 'satnogs_rigctld'
    uid: '999'
    gid: '999'
  rotctld:
    name: 'satnogs_rotctld'
    uid: '999'
    gid: '999'
  satnogs_client:
    name: 'satnogs_satnogs-client'
    uid: '999'
    gid: '999'

compose_satnogs_service_rigctld:
  image: '{{ docker_rigctld_image }}'
  container_name: '{{ compose_satnogs_params.rigctld.name }}'
  read_only: true
  user: '{{ compose_satnogs_params.rigctld.uid }}:{{ compose_satnogs_params.rigctld.gid }}'
  environment: '{{ compose_satnogs_rigctld_environment }}'
  command: 'rigctld'
  restart: 'always'

compose_satnogs_service_rotctld:
  image: '{{ docker_rotctld_image }}'
  container_name: '{{ compose_satnogs_params.rotctld.name }}'
  read_only: true
  user: '{{ compose_satnogs_params.rotctld.uid }}:{{ compose_satnogs_params.rotctld.gid }}'
  environment: '{{ compose_satnogs_rotctld_environment }}'
  command: 'rotctld'
  restart: 'always'

compose_satnogs_service_satnogs_client:
  image: '{{ docker_satnogs_client_image }}'
  container_name: '{{ compose_satnogs_params.satnogs_client.name }}'
  read_only: true
  user: '{{ compose_satnogs_params.satnogs_client.uid }}:{{ compose_satnogs_params.satnogs_client.gid }}'
  device_cgroup_rules:
    - 'c 189:* rwm'
  environment: '{{ compose_satnogs_satnogs_client_environment }}'
  command: 'satnogs-client'
  volumes:
    - type: 'tmpfs'
      target: '/tmp'
    - type: 'tmpfs'
      target: '/var/lib/satnogs-client'
    - '/dev/bus/usb:/dev/bus/usb'
  restart: 'always'

compose_satnogs:
  project_name: '{{ compose_satnogs_params.name }}'
  pull: true
  remove_orphans: true
  definition:
    version: '3.8'
    services:
      rigctld: '{{ rigctld_disabled | default(false) | ternary(omit, compose_satnogs_service_rigctld) }}'
      rotctld: '{{ rotctld_enabled | default(false) | ternary(compose_satnogs_service_rotctld, omit) }}'
      satnogs_client: '{{ compose_satnogs_service_satnogs_client }}'
