---
compose_satnogs_rigctld_environment: >-
  {% set ns = namespace(result=[]) -%}
  {% for var in rigctld_vars_map | dict2items(key_name='value', value_name='key') -%}
  {% set ns.result =
  ns.result + [{'key': var.key, 'value': lookup('ansible.builtin.vars', var.value, default=omit) | string}] -%}
  {% endfor -%}
  {{ ns.result | items2dict }}

compose_satnogs_rotctld_environment: >-
  {% set ns = namespace(result=[]) -%}
  {% for var in rotctld_vars_map | dict2items(key_name='value', value_name='key') -%}
  {% set ns.result =
  ns.result + [{'key': var.key, 'value': lookup('ansible.builtin.vars', var.value, default=omit) | string}] -%}
  {% endfor -%}
  {{ ns.result | items2dict }}

compose_satnogs_satnogs_client_environment: >-
  {% set ns = namespace(result=[]) -%}
  {% for var in satnogs_client_vars_map | dict2items(key_name='value', value_name='key') -%}
  {% set ns.result =
  ns.result + [{'key': var.key, 'value': lookup('ansible.builtin.vars', var.value, default=omit) | string}] -%}
  {% endfor -%}
  {{ ns.result | items2dict }}

compose_satnogs_params:
  name: 'satnogs'
  rigctld:
    name: 'satnogs_rigctld'
    uid: '999'
    gid: '999'
  rotctld:
    name: 'satnogs_rotctld'
    uid: '999'
    gid: '999'
  satnogs_client:
    name: 'satnogs_satnogs-client'
    uid: '999'
    gid: '999'

compose_satnogs:
  project_name: '{{ compose_satnogs_params.name }}'
  pull: true
  definition:
    version: '3.8'
    services:
      rigctld:
        image: 'librespace/hamlib:4.0'
        container_name: '{{ compose_satnogs_params.rigctld.name }}'
        read_only: true
        user: '{{ compose_satnogs_params.rigctld.uid }}:{{ compose_satnogs_params.rigctld.gid }}'
        environment: '{{ compose_satnogs_rigctld_environment }}'
        command: >-
          {{
          rigctld_disabled |
          default(false) |
          ternary('/bin/sh -c "while true; do sleep 10000; done"', 'rigctld')
          }}
        restart: 'always'
      rotctld:
        image: 'librespace/hamlib:4.0'
        container_name: '{{ compose_satnogs_params.rotctld.name }}'
        read_only: true
        user: '{{ compose_satnogs_params.rotctld.uid }}:{{ compose_satnogs_params.rotctld.gid }}'
        environment: '{{ compose_satnogs_rotctld_environment }}'
        command: >-
          {{
          rotctld_disabled |
          default(false) |
          ternary('/bin/sh -c "while true; do sleep 10000; done"', 'rotctld')
          }}
        restart: 'always'
      satnogs_client:
        image: 'librespace/satnogs-client:master'
        container_name: '{{ compose_satnogs_params.satnogs_client.name }}'
        read_only: true
        user: '{{ compose_satnogs_params.satnogs_client.uid }}:{{ compose_satnogs_params.satnogs_client.gid }}'
        device_cgroup_rules:
          - 'c 189:* rwm'
        environment: '{{ compose_satnogs_satnogs_client_environment }}'
        command: 'satnogs-client'
        volumes:
          - type: 'tmpfs'
            target: '/tmp'
          - type: 'volume'
            target: '/var/lib/satnogs-client'
          - '/dev/bus/usb:/dev/bus/usb'
        restart: 'always'
