---
satnogs_client_name: 'satnogs-client'
satnogs_client_user: 'satnogs'
satnogs_client_pypi:
  - name: 'APScheduler==3.6.3'
  - name: 'certifi==2020.11.8'
  - name: 'chardet==3.0.4'
  - name: 'cycler==0.10.0'
  - name: 'decorator==4.4.2'
  - name: 'ephem==3.7.7.1'
  - name: 'gps==3.19'
  - name: 'h5py==2.10.0'
  - name: 'idna==2.10'
  - name: 'kiwisolver==1.3.1'
  - name: 'matplotlib==3.3.2'
  - name: 'Pillow==8.0.1'
  - name: 'pyparsing==2.4.7'
  - name: 'python-dateutil==2.8.1'
  - name: 'python-dotenv==0.14.0'
  - name: 'pytz==2020.4'
  - name: 'requests==2.24.0'
  - name: 'sentry-sdk==0.18.0'
  - name: 'six==1.15.0'
  - name: 'tzlocal==2.1'
  - name: 'urllib3==1.25.11'
  - name: 'validators==0.18.1'
satnogs_client_packages:
  - name: 'git'
  - name: 'virtualenv'
  - name: 'libhdf5-103'
  - name: 'python3-gps'
  - name: 'python3-libhamlib2'
  - name: 'python3-numpy'
satnogs_client_url_unstable: 'git+https://gitlab.com/librespacefoundation/satnogs/satnogs-client.git@master'
satnogs_client_state_dir: '/tmp/.satnogs'
satnogs_client_settings:
  - satnogs_api_token
  - satnogs_pre_observation_script
  - satnogs_post_observation_script
  - satnogs_station_id
  - satnogs_station_lat
  - satnogs_station_lon
  - satnogs_station_elev
  - satnogs_app_path
  - satnogs_output_path
  - satnogs_complete_output_path
  - satnogs_incomplete_output_path
  - satnogs_remove_raw_files
  - satnogs_verify_ssl
  - satnogs_network_api_url
  - satnogs_network_api_query_interval
  - satnogs_network_api_post_interval
  - satnogs_rot_model
  - satnogs_rot_baud
  - satnogs_rot_port
  - satnogs_rig_ip
  - satnogs_rig_port
  - satnogs_rot_threshold
  - satnogs_rot_flip
  - satnogs_rot_flip_angle
  - satnogs_soapy_rx_device
  - satnogs_rx_samp_rate
  - satnogs_rx_bandwidth
  - satnogs_doppler_corr_per_sec
  - satnogs_lo_offset
  - satnogs_ppm_error
  - satnogs_gain_mode
  - satnogs_rf_gain
  - satnogs_antenna
  - satnogs_dev_args
  - satnogs_stream_args
  - satnogs_tune_args
  - satnogs_other_settings
  - satnogs_dc_removal
  - satnogs_bb_freq
  - enable_iq_dump
  - iq_dump_filename
  - disable_decoded_data
  - udp_dump_host
  - udp_dump_port
  - satnogs_waterfall_autorange
  - satnogs_waterfall_min_value
  - satnogs_waterfall_max_value
  - satnogs_artifacts_enabled
  - satnogs_artifacts_api_url
  - satnogs_artifacts_api_post_interval
  - satnogs_artifacts_api_token
  - satnogs_log_level
  - sentry_dsn
  - sentry_enabled
