---
- name: Check Ansible version
  assert:
    that: ansible_version.full is version(version_minimum, '>=')
    msg: 'Detected Ansible {{ ansible_version.full }}. This role requires Ansible {{ version_minimum }} or greater.'
- name: Check distribution
  assert:
    that: ansible_distribution == distribution and ansible_distribution_release == distribution_release
    msg: 'This role requires {{ distribution }} {{ distribution_release }}.'
- import_tasks: apt.yml
- import_tasks: packages.yml
- import_tasks: zram.yml
  when: ansible_memtotal_mb < zram_memtotal_min
