---
- name: Check Ansible version
  ansible.builtin.assert:
    that: ansible_version.full is version(version_minimum, '>=')
    msg: 'Detected Ansible {{ ansible_version.full }}. This role requires Ansible {{ version_minimum }} or greater.'
- name: Check distribution
  ansible.builtin.assert:
    that: dict(id=ansible_lsb.id, codename=ansible_lsb.codename) in lsb_compatibility
    msg: 'This role does not support {{ ansible_lsb.id }} {{ ansible_lsb.codename }}.'
- name: Import tasks packages for Debian
  ansible.builtin.import_tasks: packages.debian.yml
  when: ansible_distribution in ('Ubuntu', 'Debian')
- name: Import tasks for files
  ansible.builtin.import_tasks: files.yml
- name: Import tasks for cron
  ansible.builtin.import_tasks: cron.yml
- name: Import tasks for zram
  ansible.builtin.import_tasks: zram.yml
  when: ansible_memtotal_mb < zram_memtotal_min
