---
- name: Check Ansible version
  ansible.builtin.assert:
    that: ansible_version.full is version(version_minimum, '>=')
    msg: 'Detected Ansible {{ ansible_version.full }}. This role requires Ansible {{ version_minimum }} or greater.'
- name: Check distribution
  ansible.builtin.assert:
    that: dict(id=ansible_distribution, codename=ansible_distribution_release) in lsb_compatibility
    msg: 'This role does not support {{ ansible_distribution }} {{ ansible_distribution_release }}.'
- import_tasks: apt.yml
- import_tasks: packages.yml
- import_tasks: zram.yml
  when: ansible_memtotal_mb < zram_memtotal_min
