---
- name: Install packages
  ansible.builtin.package:
    name: '{{ item }}'
    state: 'present'
  become: true
  with_items: '{{ packages }}'
  register: res
  until: res is success
  retries: '{{ package_retries }}'
  delay: '{{ package_delay }}'
