---
- name: Gather package facts
  ansible.builtin.package_facts:
- name: Disable swap file
  ansible.builtin.service:
    name: 'dphys-swapfile'
    state: stopped
    enabled: false
  when: ('dphys-swapfile' in ansible_facts.packages)
  become: true
  tags:
    - skip_ansible_lint
- name: Add ZRAM init script
  ansible.builtin.copy:
    src: 'etc/init.d/zram'
    dest: '/etc/init.d/zram'
    mode: 0755
  become: true
  notify:
    - Start ZRAM service
