---
- name: Gather service facts
  ansible.builtin.service_facts:
- name: Disable swap file
  ansible.builtin.service:
    name: 'dphys-swapfile'
    state: stopped
    enabled: false
  when: ansible_facts.services['dphys-swapfile.service']['status'] | default('not-found') == 'enabled'
  become: true
- name: Add ZRAM init script
  ansible.builtin.copy:
    src: 'etc/init.d/zram'
    dest: '/etc/init.d/zram'
    mode: '755'
  become: true
  notify:
    - Start ZRAM service
