---
- name: Install snmpd
  ansible.builtin.package:
    name: 'snmpd'
    state: 'present'
  become: true
  register: res
  until: res is success
  retries: '{{ package_retries }}'
  delay: '{{ package_delay }}'
  notify:
    - Restart snmpd service
- name: Make snmp user member of video group
  ansible.builtin.user:
    name: 'Debian-snmp'
    groups:
      - 'video'
    append: true
    state: 'present'
  when: ansible_lsb.id == 'Raspbian'
  become: true
  notify:
    - Restart snmpd service
- name: Remove rasberry-sensors.sh script
  ansible.builtin.file:
    path: /usr/local/bin/rasberry-sensors.sh
    state: absent
  when: ansible_lsb.id == 'Raspbian'
  become: true
- name: Install raspi-sensors script
  ansible.builtin.copy:
    src: usr/local/bin/raspi-sensors
    dest: /usr/local/bin/raspi-sensors
    mode: 0755
  when: ansible_lsb.id == 'Raspbian'
  become: true
- name: Extend SNMP with raspi-sensors script OID
  ansible.builtin.blockinfile:
    path: /etc/snmp/snmpd.conf
    block: |
      extend temp /usr/local/bin/raspi-sensors temp
      extend volts_core /usr/local/bin/raspi-sensors volts core
      extend volts_sdram_c /usr/local/bin/raspi-sensors volts sdram_c
      extend volts_sdram_i /usr/local/bin/raspi-sensors volts sdram_i
      extend volts_sdram_p /usr/local/bin/raspi-sensors volts sdram_p
      extend codec_h264 /usr/local/bin/raspi-sensors codec h264
      extend codec_mpg2 /usr/local/bin/raspi-sensors codec mpg2
      extend codec_wvc1 /usr/local/bin/raspi-sensors codec wvc1
      extend codec_mpg4 /usr/local/bin/raspi-sensors codec mpg4
      extend codec_mjpg /usr/local/bin/raspi-sensors codec mjpg
      extend codec_wmv9 /usr/local/bin/raspi-sensors codec wmv9
  when: ansible_lsb.id == 'Raspbian'
  become: true
  notify:
    - Restart snmpd service
- name: Allow access to raspi-sensors script OID
  ansible.builtin.lineinfile:
    path: /etc/snmp/snmpd.conf
    line: 'view systemonly included .1.3.6.1.4.1.8072.1.3.2'
  when: ansible_lsb.id == 'Raspbian'
  become: true
  notify:
    - Restart snmpd service
- name: Setup snmpd listen configuration
  ansible.builtin.lineinfile:
    path: /etc/snmp/snmpd.conf
    regexp: '^\s*agentAddress\s'
    line: 'agentAddress {{ snmpd_agentaddress }}'
  when: snmpd_agentaddress is defined
  become: true
  tags:
    - snmpd_config
  notify:
    - Restart snmpd service
- name: Setup snmpd rocommunity configuration
  ansible.builtin.lineinfile:
    path: /etc/snmp/snmpd.conf
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  when: snmpd_rocommunity is defined
  with_items:
    - regexp: '^\s*rocommunity\s'
      line: 'rocommunity {{ snmpd_rocommunity }}'
    - regexp: '^\s*rocommunity6\s'
      line: 'rocommunity6 {{ snmpd_rocommunity }}'
  become: true
  tags:
    - snmpd_config
  notify:
    - Restart snmpd service
- name: Remove snmp user from sudoers
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    line: 'Debian-snmp ALL=(ALL) NOPASSWD: /usr/local/bin/rasberry-sensors.sh, /usr/bin/vcgencmd*'
    state: 'absent'
  when: ansible_lsb.id == 'Raspbian'
  become: true
- name: Start/stop snmpd service
  ansible.builtin.service:
    name: 'snmpd'
    enabled: '{{ snmpd_enabled | default(false) }}'
    state: '{{ "started" if snmpd_enabled | default(false) else "stopped" }}'
  become: true
  tags:
    - snmpd_config
