---
- name: Install snmpd
  package:
    name: 'snmpd'
    state: 'present'
  become: True
  register: res
  until: res is success
  retries: 3
  notify:
    - Restart snmpd service
- name: Install raspberry sensor script
  copy:
    src: usr/local/bin/rasberry-sensors.sh
    dest: /usr/local/bin/rasberry-sensors.sh
    mode: 0755
  when: ansible_lsb.id == 'Raspbian'
  become: True
- name: Extend SNMP with VideoCore script OID
  lineinfile:
    path: /etc/snmp/snmpd.conf
    line: 'extend raspberry /usr/local/bin/rasberry-sensors.sh'
  when: ansible_lsb.id == 'Raspbian'
  become: True
  notify:
    - Restart snmpd service
- name: Allow access to VideoCore script OID
  lineinfile:
    path: /etc/snmp/snmpd.conf
    line: 'view systemonly included .1.3.6.1.4.1.8072.1.3.2'
  when: ansible_lsb.id == 'Raspbian'
  become: True
  notify:
    - Restart snmpd service
- name: Setup snmpd listen configuration
  lineinfile:
    path: /etc/snmp/snmpd.conf
    regexp: '^\s*agentAddress\s'
    line: 'agentAddress {{ snmpd_agentaddress }}'
  when: snmpd_agentaddress is defined
  become: True
  tags:
    - config
  notify:
    - Restart snmpd service
- name: Setup snmpd rocommunity configuration
  lineinfile:
    path: /etc/snmp/snmpd.conf
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  when: snmpd_rocommunity is defined
  with_items:
    - regexp: '^\s*rocommunity\s'
      line: 'rocommunity {{ snmpd_rocommunity }}'
    - regexp: '^\s*rocommunity6\s'
      line: 'rocommunity6 {{ snmpd_rocommunity }}'
  become: True
  tags:
    - config
  notify:
    - Restart snmpd service
- name: Add snmp user to sudoers
  lineinfile:
    path: /etc/sudoers
    line: 'Debian-snmp ALL=(ALL) NOPASSWD: /usr/local/bin/rasberry-sensors.sh, /usr/bin/vcgencmd*'
  when: ansible_lsb.id == 'Raspbian'
  become: True
- name: Start/stop snmpd service
  service:
    name: 'snmpd'
    enabled: '{{ snmpd_enabled | default(False) }}'
    state: '{{ "started" if snmpd_enabled | default(False) else "stopped" }}'
  become: True
  tags:
    - config
