---
- name: Install snmpd
  package:
    name: 'snmpd'
    state: 'present'
  become: True
  register: res
  until: res is success
  retries: 3
- name: Install raspberry sensor script
  copy:
    src: usr/local/bin/rasberry-sensors.sh
    dest: /usr/local/bin/rasberry-sensors.sh
    mode: 0755
  when: ansible_lsb.id == 'Raspbian'
  become: True
- name: Setup snmpd rpi script
  lineinfile:
    path: /etc/snmp/snmpd.conf
    line: 'extend raspberry /usr/local/bin/rasberry-sensors.sh'
  when: ansible_lsb.id == 'Raspbian'
  become: True
- name: Setup snmpd listen configuration
  lineinfile:
    path: /etc/snmp/snmpd.conf
    regexp: '^( )*agentAddress .*'
    line: 'agentAddress {{ snmpd_agentaddress }}'
  when: snmpd_agentaddress is defined
  become: True
- name: Setup snmpd rocommunity configuration
  lineinfile:
    path: /etc/snmp/snmpd.conf
    regexp: '^( )*rocommunity .*'
    line: 'rocommunity {{ snmpd_rocommunity }}'
  when: snmpd_rocommunity is defined
  become: True
  notify:
    - Restart snmpd service
- name: Add snmp user to sudoers
  lineinfile:
    path: /etc/sudoers
    line: 'Debian-snmp ALL=(ALL) NOPASSWD: /usr/local/bin/rasberry-sensors.sh, /usr/bin/vcgencmd*'
  when: ansible_lsb.id == 'Raspbian'
  become: True
  notify:
    - Restart snmpd service
- name: Start/stop snmpd service
  systemd:
    daemon_reload: True
    name: 'snmpd'
    enabled: '{{ snmpd_enabled | default(False) }}'
    state: '{{ "started" if snmpd_enabled | default(False) else "stopped" }}'
  become: True
  tags:
    - config
