---
package_retries: '3'
package_delay: '1'
satnogs_client_name: 'satnogs-client'
satnogs_client_user: 'satnogs'
satnogs_client_packages:
  - name: 'git'
  - name: 'pkg-config'
  - name: 'virtualenv'
  - name: 'libatlas3-base'
  - name: 'libhdf5-103-1'
  - name: 'python3-gps'
  - name: 'python3-libhamlib2'
satnogs_client_pypi: >-
  {{
  lookup('ansible.builtin.file', 'requirements.txt').splitlines() |
  map('trim') |
  map('regex_search', '^(?!#).*$') |
  select('string') |
  reject('eq', '') |
  list
  }}
satnogs_client_url_unstable: 'git+https://gitlab.com/librespacefoundation/satnogs/satnogs-client.git@master'
satnogs_client_state_dir: '/tmp/.satnogs'
satnogs_client_settings:
  - satnogs_api_token
  - satnogs_pre_observation_script
  - satnogs_post_observation_script
  - satnogs_station_id
  - satnogs_station_lat
  - satnogs_station_lon
  - satnogs_station_elev
  - satnogs_gpsd_client_enabled
  - satnogs_gpsd_host
  - satnogs_gpsd_port
  - satnogs_gpsd_timeout
  - satnogs_app_path
  - satnogs_output_path
  - satnogs_complete_output_path
  - satnogs_incomplete_output_path
  - satnogs_remove_raw_files
  - satnogs_keep_artifacts
  - satnogs_artifacts_output_path
  - satnogs_verify_ssl
  - satnogs_network_api_url
  - satnogs_network_api_query_interval
  - satnogs_network_api_post_interval
  - satnogs_rot_enabled
  - satnogs_rot_model
  - satnogs_rot_baud
  - satnogs_rot_port
  - satnogs_rot_threshold
  - satnogs_rot_flip
  - satnogs_rot_flip_angle
  - satnogs_rig_ip
  - satnogs_rig_port
  - satnogs_soapy_rx_device
  - satnogs_rx_samp_rate
  - satnogs_rx_bandwidth
  - satnogs_doppler_corr_per_sec
  - satnogs_lo_offset
  - satnogs_ppm_error
  - satnogs_gain_mode
  - satnogs_rf_gain
  - satnogs_antenna
  - satnogs_dev_args
  - satnogs_stream_args
  - satnogs_tune_args
  - satnogs_other_settings
  - satnogs_dc_removal
  - satnogs_bb_freq
  - enable_iq_dump
  - iq_dump_filename
  - disable_decoded_data
  - udp_dump_host
  - udp_dump_port
  - satnogs_upload_audio_files
  - satnogs_upload_waterfall_files
  - satnogs_waterfall_autorange
  - satnogs_waterfall_min_value
  - satnogs_waterfall_max_value
  - satnogs_artifacts_enabled
  - satnogs_artifacts_api_url
  - satnogs_artifacts_api_post_interval
  - satnogs_artifacts_api_token
  - satnogs_log_level
  - satnogs_scheduler_log_level
  - sentry_dsn
  - sentry_enabled
  - satnogs_upload_audio_files
  - satnogs_upload_waterfall_files
