---
package_retries: '3'
package_delay: '1'
satnogs_client_name: 'satnogs-client'
satnogs_client_user: 'satnogs'
satnogs_client_pypi:
  # This list is a copy of satnogs-client:requirements.txt
  - name: 'APScheduler==3.9.1'
  - name: 'Pillow==9.2.0'
  - name: 'certifi==2022.6.15'
  - name: 'charset-normalizer==2.1.0'
  - name: 'cycler==0.11.0'
  - name: 'decorator==5.1.1'
  - name: 'ephem==4.1.3'
  - name: 'fonttools==4.34.4'
  - name: 'h5py==3.7.0'
  - name: 'idna==3.3'
  - name: 'kiwisolver==1.4.4'
  - name: 'matplotlib==3.5.2'
  - name: 'numpy==1.23.1'
  - name: 'packaging==21.3'
  - name: 'pyparsing==3.0.9'
  - name: 'python-dateutil==2.8.2'
  - name: 'python-dotenv==0.20.0'
  - name: 'pytz-deprecation-shim==0.1.0.post0'
  - name: 'pytz==2022.1'
  - name: 'requests==2.28.1'
  - name: 'sentry-sdk==1.6.0'
  - name: 'six==1.16.0'
  - name: 'tzdata==2022.1'
  - name: 'tzlocal==4.2'
  - name: 'urllib3==1.26.10'
  - name: 'validators==0.20.0'
satnogs_client_packages:
  - name: 'git'
  - name: 'pkg-config'
  - name: 'virtualenv'
  - name: 'libhdf5-dev'
  - name: 'python3-gps'
  - name: 'python3-libhamlib2'
satnogs_client_url_unstable: 'git+https://gitlab.com/librespacefoundation/satnogs/satnogs-client.git@master'
satnogs_client_state_dir: '/tmp/.satnogs'
satnogs_client_settings:
  - satnogs_api_token
  - satnogs_pre_observation_script
  - satnogs_post_observation_script
  - satnogs_station_id
  - satnogs_station_lat
  - satnogs_station_lon
  - satnogs_station_elev
  - satnogs_app_path
  - satnogs_output_path
  - satnogs_complete_output_path
  - satnogs_incomplete_output_path
  - satnogs_remove_raw_files
  - satnogs_verify_ssl
  - satnogs_network_api_url
  - satnogs_network_api_query_interval
  - satnogs_network_api_post_interval
  - satnogs_rot_model
  - satnogs_rot_baud
  - satnogs_rot_port
  - satnogs_rig_ip
  - satnogs_rig_port
  - satnogs_rot_threshold
  - satnogs_rot_flip
  - satnogs_rot_flip_angle
  - satnogs_soapy_rx_device
  - satnogs_rx_samp_rate
  - satnogs_rx_bandwidth
  - satnogs_doppler_corr_per_sec
  - satnogs_lo_offset
  - satnogs_ppm_error
  - satnogs_gain_mode
  - satnogs_rf_gain
  - satnogs_antenna
  - satnogs_dev_args
  - satnogs_stream_args
  - satnogs_tune_args
  - satnogs_other_settings
  - satnogs_dc_removal
  - satnogs_bb_freq
  - enable_iq_dump
  - iq_dump_filename
  - disable_decoded_data
  - udp_dump_host
  - udp_dump_port
  - satnogs_waterfall_autorange
  - satnogs_waterfall_min_value
  - satnogs_waterfall_max_value
  - satnogs_artifacts_enabled
  - satnogs_artifacts_api_url
  - satnogs_artifacts_api_post_interval
  - satnogs_artifacts_api_token
  - satnogs_log_level
  - sentry_dsn
  - sentry_enabled
  - satnogs_upload_audio_files
  - satnogs_upload_waterfall_files
